language: bash
services: docker

env:
  - VERSION=1.5.0 FOLDER=1.x.x
  - VERSION=1.4.0 FOLDER=1.x.x
  - VERSION=1.3.0 FOLDER=1.x.x

before_script:
  - env | sort
  - cd ${FOLDER}
  - image="nifi:${VERSION}"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
