language: bash
services: docker

branches:
  only:
    - master

env:
  - VERSION=1.7.0 FOLDER=1.x.x LATEST=true
  - VERSION=1.6.0 FOLDER=1.x.x
  - VERSION=1.5.0 FOLDER=1.x.x
  - VERSION=1.4.0 FOLDER=1.x.x
  - VERSION=1.3.0 FOLDER=1.x.x

before_script:
  - env | sort
  - cd ${FOLDER}
  - image="${DOCKERHUB_USERNAME}/nifi:${VERSION}"
  - latest="${DOCKERHUB_USERNAME}/nifi:latest"

script:
  - docker build --build-arg VERSION=${VERSION} -t "$image" .
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  - docker push "$image"
  - |
    if [ "$LATEST" == "true" ]; then
      docker tag "$image" "$latest"
      docker push "$latest" 
    fi


after_script:
  - docker images
