language: bash
services: docker

env:
  - VERSION=1.5.0 FOLDER=1.x.x
  - VERSION=1.4.0 FOLDER=1.x.x
  - VERSION=1.3.0 FOLDER=1.x.x

before_script:
  - env | sort
  - cd ${FOLDER}
  - image="${DOCKERHUB_USERNAME}/nifi:${VERSION}"

script:
  - docker build --build-arg VERSION=${VERSION} -t "$image" .
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  - docker push "$image"

after_script:
  - docker images
