version: '3'
services:
    nifi1:
        image: jllacer/nifi:1.3.0
        ports:
            - 8081:8080
        networks:
            - nifi
        volumes:
            - nifi-1-flowfile_repository:/opt/nifi/flowfile_repository
            - nifi-1-database_repository:/opt/nifi/database_repository
            - nifi-1-content_repository:/opt/nifi/content_repository
            - nifi-1-provenance_repository:/opt/nifi/provenance_repository
        environment:
            NODE_HOSTNAME: nifi1
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=nifi2:2888:3888 server.3=nifi3:2888:3888
            ZOO_CONNECT: nifi1:2181,nifi2:2181,nifi3:2181

    nifi2:
        image: jllacer/nifi:1.3.0
        ports:
            - 8082:8080
        networks:
            - nifi
        volumes:
            - nifi-2-flowfile_repository:/opt/nifi/flowfile_repository
            - nifi-2-database_repository:/opt/nifi/database_repository
            - nifi-2-content_repository:/opt/nifi/content_repository
            - nifi-2-provenance_repository:/opt/nifi/provenance_repository
        environment:
            NODE_HOSTNAME: nifi2
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=nifi1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=nifi3:2888:3888
            ZOO_CONNECT: nifi1:2181,nifi2:2181,nifi3:2181

    nifi3:
        image: jllacer/nifi:1.3.0
        ports:
            - 8083:8080
        networks:
            - nifi
        volumes:
            - nifi-3-flowfile_repository:/opt/nifi/flowfile_repository
            - nifi-3-database_repository:/opt/nifi/database_repository
            - nifi-3-content_repository:/opt/nifi/content_repository
            - nifi-3-provenance_repository:/opt/nifi/provenance_repository
        environment:
            NODE_HOSTNAME: nifi3
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=nifi1:2888:3888 server.2=nifi2:2888:3888 server.3=0.0.0.0:2888:3888
            ZOO_CONNECT: nifi1:2181,nifi2:2181,nifi3:2181

networks:
    nifi:

volumes:
    nifi-1-flowfile_repository:
        driver: cloudstor:aws
    nifi-1-database_repository:
        driver: cloudstor:aws
    nifi-1-content_repository:
        driver: cloudstor:aws
    nifi-1-provenance_repository:
        driver: cloudstor:aws
    nifi-2-flowfile_repository:
        driver: cloudstor:aws
    nifi-2-database_repository:
        driver: cloudstor:aws
    nifi-2-content_repository:
        driver: cloudstor:aws
    nifi-2-provenance_repository:
        driver: cloudstor:aws
    nifi-3-flowfile_repository:
        driver: cloudstor:aws
    nifi-3-database_repository:
        driver: cloudstor:aws
    nifi-3-content_repository:
        driver: cloudstor:aws
    nifi-3-provenance_repository:
        driver: cloudstor:aws
